export const questionsBank = [
  {
    Id: "22",
    Name:
      "Before going back to Heaven, what did Jesus tell the disciples NOT to do?",
    A: "Not to wait, but start preaching",
    B: "Not to go back to fishing",
    C: "Not to betray Jesus anymore",
    D: "Not to move away from Jerusalem",
    Answer: "D",
    Points: 1,
  },
  {
    Id: "6",
    Name: "What is a witness?",
    A: "A person who doesn't say much",
    B: "A person who tells what they saw",
    C: "A person who tells an imaginary story",
    D: "None of this is correct",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "21",
    Name:
      "The Holy Spirit was poured out on a festival day. What is the name of the festival?",
    A: "The New Moon",
    B: "The Unleavened Bread",
    C: "The Pentecost",
    D: "The Passover",
    Answer: "C",
    Points: 1,
  },
  {
    Id: "15",
    Name: "What is the name of the person who gets selected to replace Judas?",
    A: "Barnabas",
    B: "Matthew",
    C: "Mark",
    D: "None of them",
    Answer: "D",
    Points: 1,
  },
  {
    Id: "1",
    Name:
      "Before Jesus went back to Heaven, he said the disciples would receive something. What is it?",
    A: "Wisdom",
    B: "The Holy Spirit",
    C: "Wealth and money",
    D: "Political power",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "10",
    Name: "What did the crippled man do for living?",
    A: "He does busking on the street",
    B: "He pickpockets other people",
    C: "He asks for money",
    D: "None of the above",
    Answer: "A",
    Points: 1,
  },
  {
    Id: "20",
    Name:
      "When the rulers captured Peter and John, they commanded them to stop doing 1 thing. What is it?",
    A: "Stop sinning",
    B: "Stop preaching",
    C: "Stop healing",
    D: "Stop praying",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "18",
    Name:
      "The crippled man and Peter and John met in front of the temple. How long has he been like that?",
    A: "From a young age",
    B: "For about a few years",
    C: "Since he started getting old",
    D: "None of the above",
    Answer: "A",
    Points: 1,
  },
  {
    Id: "28",
    Name: "According to Peter, what is the reason the crippled man got healed?",
    A: "Because the crippled man is a sinner",
    B: "Because God loves to heal people",
    C: "Because of faith in Jesus's name",
    D: "All of the above",
    Answer: "C",
    Points: 1,
  },
  {
    Id: "5",
    Name:
      "Judas received some money for betraying Jesus, what did he do with that money?",
    A: "He bought a piece of land",
    B: "He bought animals to sacrifice for his sins",
    C: "He gave to the poor",
    D: "He didn't do anything",
    Answer: "A",
    Points: 1,
  },
  {
    Id: "17",
    Name:
      "When the disciples started to speak in tongues, some people mocked. What did the mockers say?",
    A: "These people are wierdos",
    B: "These people drank too much",
    C: "These people didn't sleep enough",
    D: "These people didn't drink enough",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "7",
    Name:
      "When some people were mocking at the outpouring of the Holy Spirit, who stood up to explain?",
    A: "John",
    B: "Peter",
    C: "Matthias",
    D: "James",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "3",
    Name:
      "Recite Acts 1:8 (What was Jesus' last words to the disciples about the Holy Spirit?)",
    A: "",
    B: "",
    C: "",
    D: "",
    Answer: "",
    Points: 1,
  },
  {
    Id: "14",
    Name: "How did they decide which man to replace Judas?",
    A: "They cast lots",
    B: "They did paper scissor rock",
    C: "They voted",
    D: "They asked Jesus to pick",
    Answer: "A",
    Points: 1,
  },
  {
    Id: "13",
    Name: "What is the name of the person who suggested about replacing Judas?",
    A: "Matthias",
    B: "Peter",
    C: "Jesus",
    D: "None of the above",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "9",
    Name:
      "When the rulers knew about this, what did they do to Peter and John?",
    A: "They laughed at Peter and John",
    B: "They threw rocks at Peter and John",
    C: "They killed Peter and John",
    D: "The arrested Peter and John",
    Answer: "D",
    Points: 1,
  },
  {
    Id: "31",
    Name: "From Acts chapter 1, what is the 3P’s?",
    A: "Praise, Power, Patience",
    B: "Promise, Patience, Power",
    C: "Prayer, Praise and Perseverance",
    D: "Promise, Power and Persistence",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "4",
    Name: "What did Judas do to Jesus?",
    A: "Judas killed Jesus",
    B: "Judas betrayed Jesus",
    C: "Judas arrested Jesus",
    D: "All of the above",
    Answer: "B",
    Points: 1,
  },
  {
    Id: "6",
    Name: "How did Judas die?",
    A: "He got sick and passed away",
    B: "King Herod killed him",
    C: "He hanged himself because of guilt",
    D: "He got old and just died",
    Answer: "C",
    Points: 1,
  },
  {
    Id: "16",
    Name:
      "The Bible said the crowds were confused at the outpouring of the Holy Spirit, why?",
    A: "Because they thought the people were drunk",
    B: "Because they were afraid",
    C: "Because they heard people praised God in different languages",
    D: "Because they saw fires are burning everywhere",
    Answer: "C",
    Points: 1,
  },
  {
    Id: "8",
    Name:
      "When the people saw the crippled man got healed, how did they respond?",
    A: "They were amazed",
    B: "They ran and saw him",
    C: "They did not understand how the man got healed",
    D: "All of the above",
    Answer: "D",
    Points: 1,
  },
  {
    Id: "2",
    Name:
      "What are the places that Jesus told his disciples to be his witness?",
    A: "Jerusalem",
    B: "Samaria & Judea",
    C: "The rest of the world",
    D: "All of them",
    Answer: "D",
    Points: 1,
  },
  {
    Id: "19",
    Name: "What happen to the crippled man when he got healed?",
    A: "He jumped",
    B: "He danced",
    C: "He sang",
    D: "He showed himself to people",
    Answer: "A",
    Points: 1,
  },
  {
    Id: "7",
    Name: "Recite Acts 3:6 (What did Peter said to the crippled man?)",
    A: "",
    B: "",
    C: "",
    D: "",
    Answer: "",
    Points: 1,
  },
  {
    Id: "25",
    Name:
      "On the day of Pentecost, the disciples came together. What did they do on that day?",
    A: "They sang songs and worshipped God",
    B: "They ate the Passover",
    C: "They prayed in unity",
    D: "They taught God's word with power",
    Answer: "C",
    Points: 1,
  },
  {
    Id: "3A",
    Name:
      "Jesus was taken up in the cloud. The disciples kept watching until someone appeared. Who were these people?",
    A: "The people that got healed",
    B: "The rulers",
    C: "The angels",
    D: "The children whom Jesus loved",
    Answer: "C",
    Points: 1,
  },
  {
    Id: "11",
    Name:
      "Jesus said when the Holy Spirit has come upon the disciples, what would they become?",
    A: "Pastors of churches",
    B: "Fishermen",
    C: "Witnesses for Jesus",
    D: "Missionaries",
    Answer: "C",
    Points: 1,
  },
  {
    Id: "30",
    Name:
      'After the rulers had captured Peter and John, they asked them: "By what .... you have done this?"',
    A: "Position",
    B: "Ability",
    C: "Right",
    D: "Name",
    Answer: "D",
    Points: 1,
  },
  {
    Id: "12",
    Name:
      "Recite Acts 4:20 (When the rulers warned Peter and John to stop teaching about Jesus, what did they say?)",
    A: "",
    B: "",
    C: "",
    D: "",
    Answer: "",
    Points: 1,
  },
  {
    Id: "23",
    Name:
      "Fill in the blanks, Jesus said to his disciples: “For ….. baptised with water, but ….. shall be baptised with the Holy Spirit”",
    A: "John, I",
    B: "Jesus, you",
    C: "John, you",
    D: "Jesus, John",
    Answer: "C",
    Points: 5,
  },
  {
    Id: "40",
    Name:
      "Before going back to Heaven, Jesus told the disciples not to go away from Jerusalem. Why?",
    A: "Because Jerusalem is the capital of Israel",
    B: "Because Jerusalem is where Jesus died and came back to life",
    C:
      "Because Jerusalem will be where the disciples will receive the Holy Spirit",
    D: "None of this is correct",
    Answer: "C",
    Points: 5,
  },
  {
    Id: "37",
    Name:
      "When the people asked Peter about how to get saved, what did he say?",
    A: "Believe, repent and receive the Holy Spirit",
    B: "Pray to Jesus always",
    C: "Follow Jesus & do good deeds",
    D: "Preaching Jesus by the power of the Holy Spirit",
    Answer: "A",
    Points: 5,
  },
  {
    Id: "41",
    Name:
      "After Jesus was taken up, what did the disciples did not do straight away?",
    A: "They went back to Jerusalem",
    B: "They prayed",
    C: "They worshipped God together",
    D: "They went everywhere and told people about Jesus’s resurrection",
    Answer: "D",
    Points: 5,
  },
  {
    Id: "29",
    Name:
      "Questioning Peter and John, the rulers were amazed at their answer, why?",
    A: "Because Peter and John had power to heal the man",
    B: "Because Peter and John spoke with big words",
    C: "Because Peter and John were uneducated ordinary people",
    D: "Because Peter and John were humble before them",
    Answer: "C",
    Points: 5,
  },
  {
    Id: "43",
    Name: "When the crowds heard this sound, what did they not do?",
    A: "They ran to see what's going on",
    B: "They worshipped God with the disciples",
    C: "They asked questions",
    D: "They mocked",
    Answer: "B",
    Points: 5,
  },
  {
    Id: "33",
    Name:
      "What are the names of people who did not get selected to replace Judas?",
    A: "Barnabas",
    B: "Peter",
    C: "Luke",
    D: "All of them",
    Answer: "D",
    Points: 5,
  },
  {
    Id: "34",
    Name: "When the Holy Spirit come, what fell on the disciples?",
    A: "Tongues of fire",
    B: "The Holy Spirit",
    C: "Power",
    D: "All of them",
    Answer: "D",
    Points: 5,
  },
  {
    Id: "36",
    Name: "When Peter finished his sermon, what happened to the people?",
    A: "They became angry at Peter",
    B: "They felt guilty for their sins",
    C: "They rejoiced because Jesus was alive",
    D: "All of the above",
    Answer: "B",
    Points: 5,
  },
  {
    Id: "24",
    Name:
      "What did Peter say about the requirements for the person would replace Judas?",
    A: "They must be with Jesus during his trial",
    B: "They must be with Jesus from the very beginning",
    C: "They must have a revelation that Jesus is God",
    D: "The must see at the tomb when Jesus came back to life",
    Answer: "B",
    Points: 5,
  },
  {
    Id: "27",
    Name:
      "Peter mentioned the king David. What did king David say about the Messiah?",
    A: "That the Messiah will never physically die",
    B: "That the Messiah would rise again from death",
    C: "That Messiah will never grow old and die",
    D: "None of the above",
    Answer: "B",
    Points: 5,
  },
  {
    Id: "42",
    Name:
      "When the Holy Spirit came upon the disciples, what did they start doing?",
    A: "They started to dance",
    B: "They started to learn new languages",
    C: "They prophesied about the future",
    D: "They declared the wonder of God",
    Answer: "D",
    Points: 5,
  },
  {
    Id: "26",
    Name: "When the Holy Spirit come, what did it sound like?",
    A: "Running water",
    B: "Strong blow of air",
    C: "Falling rocks",
    D: "Explosion of fire",
    Answer: "B",
    Points: 5,
  },
  {
    Id: "35",
    Name:
      "To explain to the crowds what's going on, Peter mentioned the prophet Joel. What did the prophet Joel predict about the last day?",
    A: "People will go to church no more",
    B: "People will speak in heavenly language",
    C: "People will turn away from God",
    D: "People will be coming to God in great numbers",
    Answer: "B",
    Points: 5,
  },
  {
    Id: "70",
    Name:
      'Fill in the blank: When Peter was questioned by the rulers, he said "The .... that you builders .... has now become the ....."',
    A: "",
    B: "",
    C: "",
    D: "",
    Answer: "stone, rejected, cornerstone",
    Points: 5,
  },
  {
    Id: "38",
    Name: "After Peter and John got released, where did they go?",
    A: "They went back to the church building",
    B: "They returned home",
    C: "They went to meet other believers",
    D: "They went and preached Jesus",
    Answer: "C",
    Points: 5,
  },
  {
    Id: "44",
    Name:
      "After Peter and John got released, the church prayed and asked God for 1 thing. What was it?",
    A: "Wisdom for future street outreach",
    B: "The ability to gain more influence",
    C: "The ability to tell God's message with courage",
    D: "Protection from the rulers",
    Answer: "C",
    Points: 5,
  },
];
